language: java
os: linux
jobs:
  include:
    - stage: test
      script: mvn clean verify
    - stage: build
      script: docker build -t nijadev69/sample-application-http-api-server:1.0 ./sample-application-http-api-server/
      script: docker build -t nijadev69/sample-application-db-changelog-job:1.0 ./sample-application-db-changelog-job/
    - stage: push
      script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script: docker push nijadev69/sample-application-http-api-server
      script: docker push nijadev69/sample-application-db-changelog-job

